export { ConfigEmpresaFiliais, ConfigEmpresaEquipe, ConfigEmpresaPermissoes, ConfigEmpresaCargos, ConfigNichos } from "./sections/SettingsEmpresa";
export { ConfigCRMCampos, ConfigCRMFunis, ConfigCRMOrigens, ConfigCRMProdutos } from "./sections/SettingsCRM";
export { ConfigCRMSLA } from "./sections/SettingsCRMSLA";
export { ConfigCRMGatilhosIA } from "./sections/SettingsCRMGatilhosIA";
export { ConfigProdutividadeCategorias, ConfigFinanceiroCategorias, ConfigFinanceiroSquads } from "./sections/SettingsProdutividade";
export { ConfigFinanceiroBloqueioPeriodo, ConfigFinanceiroAuditoria } from "./sections/SettingsFinanceiroGovernanca";
export { ConfigEngajamentoModelos, ConfigEngajamentoAutomacoes, ConfigBusinessDashboard } from "./sections/SettingsEngajamento";
export { ConfigIntegracoesApps, ConfigIntegracoesSMTP, ConfigIntegracoesSDR } from "./sections/SettingsIntegracoes";
export { ConfigNotificacoesPreferencias } from "./sections/SettingsNotificacoes";
export { ConfigPerfilUsuario } from "./sections/usuario/ConfigPerfilUsuario";
export { ConfigPreferenciasSistema } from "./sections/usuario/ConfigPreferenciasSistema";
export { ConfigSistemaBackups, ConfigSistemaAuroraUso } from "./sections/SettingsSistema";
export { ConfigSistemaConhecimentoIA } from "./sections/SettingsSistemaConhecimento";
export { ConfigSistemaAprendizados } from "./sections/SettingsSistemaAprendizados";
export { ConfigRodizioLeads } from "./sections/SettingsRodizioLeads";
export { ConfigKanbanBoards } from "./sections/SettingsKanbanBoards";
